name: resource_handler
description: "A Flutter project to handle image in our project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  image: any
  analyzer_query:
    path: extern/analyzer_query

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any


flutter:
  assets:
    - lib/resources/images/3.0x/
    - lib/resources/images/2.0x/
    - lib/resources/images/
  uses-material-design: true